---
language: ruby
cache: bundler

matrix:
  include:
    - rvm: 1.9.3
      env: PUPPET_VERSION='2.7.26'
      services: docker
      script: bundle exec rake check
    - rvm: 1.9.3
      env: PUPPET_VERSION='3.7.5'
      services: docker
      script: bundle exec rake check
    - rvm: 2.2
      env: PUPPET_VERSION='4.5'
      services: docker
      script: bundle exec rake check
    - rvm: 2.2
      env: PUPPET_VERSION='4.6.1'
      services: docker
      script: bundle exec rake check
  allow_failures:
    - rvm: 1.9.3
      env: PUPPET_VERSION=2.7.26
    - rvm: 1.9.3
      env: PUPPET_VERSION=3.7.5

notifications:
  email:
    on_failure: always
